# Proyecto Introducción a la Ciencia de los Datos
**José Barrios - 20007192**

## Descripción general
El proyecto consiste en aplicar los conocimientos aprendidos en clase (y apoyándose de referencias adicionales útiles) para crear modelos predictivos de regresión lineal uni-variable sencillos de la forma:
> y = f(x) = mx +b

Donde:
<br>y = la variable dependiente
<br>x = variable independiente
<br>m = pendiente de la recta(parámetro del modelo)
<br>b = intercepto(parámetro del modelo)

Tanto “x” como “y” son parte del dataset usado , “m” y “b” son parámetros del modelo los cuales buscamos estimar con los datos, esto significa que se busca encontrar que valores de “m” y “b” producen una recta que describa de la mejor manera posible la relación entre los datos "x" y "y".

### Pasos solicitados
Los datos se encuentran dados en el formato binario de NumPy .npy por lo tanto usaremos la función “load” de numpy para poderlos utilizar:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html

Instalar Numpy, Pandas, Seaborn para el notebook

In [21]:
import numpy as np
import seaborn as sns
import pandas as pd

In [2]:
data = np.load('proyecto_training_data.npy')

In [29]:
#'Revolvemos' la data para minimizar algún tipo de sesgo
#Esto reordena las filas, pero los valores en cada columna siguen siendo los mismos
np.random.shuffle(data)
data

array([[1.560e+05, 6.000e+00, 1.026e+03, 5.000e+00, 1.969e+03, 6.100e+01],
       [2.450e+05, 8.000e+00, 1.563e+03, 6.000e+00, 2.007e+03, 7.800e+01],
       [8.800e+04, 6.000e+00, 5.250e+02, 6.000e+00, 1.971e+03, 2.100e+01],
       ...,
       [3.930e+04, 1.000e+00, 3.340e+02, 2.000e+00, 1.946e+03, 5.000e+01],
       [1.299e+05, 5.000e+00, 8.640e+02, 5.000e+00, 1.958e+03, 7.000e+01],
       [2.260e+05, 7.000e+00, 1.057e+03, 7.000e+00, 2.001e+03,       nan]])

Procedemos a dividir la data en dos secciones: una para entrenamiento y otra para verificación del modelo.

Así que se procede a determinar cuántas filas tiene la data y así separar el 80% de ella para entrenamiento.

In [30]:
filas_entrenamiento = int(len(data) * 0.8)

print("Forma o tamaño: ", data.shape)
print("Filas para entrenamiento: ", filas_entrenamiento)

Forma o tamaño:  (1460, 6)
Filas para entrenamiento:  1168


In [31]:
data_entrenamiento = data[:filas_entrenamiento]

print("Forma o tamaño de data de entrenamiento: ", data_entrenamiento.shape)

Forma o tamaño de data de entrenamiento:  (1168, 6)


## Análisis exploratorio
Usando numpy, calcular los siguientes valores de cada variable de la data.
* Media
* Valor máximo
* Valor mínimo
* Rango
* Desviación estándar

In [32]:
print('Madia: ', np.nanmean(data_entrenamiento, axis=0))
print('Máximo: ', np.nanmax(data_entrenamiento, axis=0))
print('Mínimo: ', np.nanmin(data_entrenamiento, axis=0))
print('Rango: ', np.ptp(data_entrenamiento, axis=0))
print('Desviación estándar: ', np.nanstd(data_entrenamiento, axis=0))

Madia:  [1.82531962e+05 6.11130137e+00 1.16568579e+03 6.53767123e+00
 1.97165839e+03 6.99770594e+01]
Máximo:  [7.550e+05 1.000e+01 3.228e+03 1.200e+01 2.010e+03 1.820e+02]
Mínimo:  [3.490e+04 1.000e+00 3.720e+02 3.000e+00 1.872e+03 2.100e+01]
Rango:  [7.201e+05 9.000e+00 2.856e+03 9.000e+00 1.380e+02       nan]
Desviación estándar:  [8.06278187e+04 1.37912855e+00 3.82951982e+02 1.59471045e+00
 3.01603122e+01 2.21939384e+01]


Para cada variable en el dataset usar seaborn (función distplot https://seaborn.pydata.org/generated/seaborn.distplot.html) para graficar un histograma de la variable.

array([[0.25554659, 0.10918154],
       [0.53166174, 0.99599467],
       [0.98527497, 0.71739491],
       [0.29706317, 0.3585277 ],
       [0.20554437, 0.22902848],
       [0.54641557, 0.31639087]])

array([[0.29706317, 0.3585277 ],
       [0.20554437, 0.22902848],
       [0.54641557, 0.31639087],
       [0.98527497, 0.71739491],
       [0.25554659, 0.10918154],
       [0.53166174, 0.99599467]])